from enum import Enum

__NAMESPACE__ = "http://eop-cfi.esa.int/CFI"


class AocsType(Enum):
    VALUE_0 = "0"
    GEOCENTRIC_POINTING = "GEOCENTRIC_POINTING"
    VALUE_1 = "1"
    LOCAL_NORMAL_POINTING = "LOCAL_NORMAL_POINTING"
    VALUE_2 = "2"
    YAW_STEERING_MODE = "YAW_STEERING_MODE"
    VALUE_3 = "3"
    ZERO_DOPPLER_YSM = "ZERO_DOPPLER_YSM"
